#!/usr/bin/env bash
# This script generates a story based on the content of /etc/passwd.

while IFS=':' read -r username _ userid groupid _ home shell; do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
  echo "USER ID's place is protected by the passcode PASSWORD, more info about the user here: https://someinfo.com/$userid"
  echo "--------------------------------------------------------"
done < /etc/passwd
