#!/usr/bin/env bash
# This script generates a story based on the content of /etc/passwd.

while IFS=':' read -r username _ userid _ _ home shell _; do
  echo "The user $username:x:$userid is part of the gang, lives in $home and rides $shell."
  echo "$userid's place is protected by the passcode , more info about the user here $uinfo"
  echo "--------------------------------------------------------"
done < /etc/passwd
