#!/usr/bin/env bash
# This script displays numbers and messages based on the loop iteration number.

counter=1

while [ "$counter" -le 20 ]; do
  case "$counter" in
    4)
      echo "$counter and then bad luck from China"
      ;;
    9)
      echo "$counter and then bad luck from Japan"
      ;;
    17)
      echo "$counter and then bad luck from Italy"
      ;;
    *)
      echo "$counter"
      ;;
  esac
  counter=$((counter + 1))
done
