#!/usr/bin/env bash
# This script displays time in the format HH:MM for 12 hours and 59 minutes.

hour=0

while [ "$hour" -lt 12 ]; do
  minute=1
  while [ "$minute" -le 59 ]; do
    printf "%02d:%02d\n" "$hour" "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
