#!/usr/bin/env bash
#This script manages another file
start_process() {
  while :
  do
    echo "I am alive!"
    sleep 2
  done > /tmp/my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"
}

# Function to stop the process
stop_process() {
  if [ -e "/var/run/my_process.pid" ]; then
    pid=$(cat /var/run/my_process.pid)
    kill "$pid" && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
  fi
}

command="$1"

if [ -z "$command" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [ "$command" = "start" ]; then
  start_process

elif [ "$command" = "stop" ]; then
  stop_process

elif [ "$command" = "restart" ]; then
  stop_process
  start_process
  echo "manage_my_process restarted"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
