#!/usr/bin/env bash
#Printing and managing my process script

case "$1" in
  start)
    ./manage_my_process.sh start
    ;;
  stop)
    ./manage_my_process.sh stop
    ;;
  restart)
    ./manage_my_process.sh restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0 
